### ISSUE TITLE
startpage-zlb needs to be migrated to haul

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/haul#163]
The start migration excluded start.mozilla.com which needs to be added to our Apache configuration (and potentially the Traefik config for certs). Once this has been pushed into the production environment, we need to update the DNS record.

**Comment by floatingatoll** [comment]
The affected hostnames are:

```
start.mozilla.com
*.start.mozilla.com
*.start2.mozilla.com
*.start3.mozilla.com
```

These hostnames used to be hosted on Generic cluster, I believe in either /genericrhel6/ or /startpage/. They are _not_ handled the same as `start.mozilla.org`, and have a different Rewrite/Redirect. Please spelunk IT puppet for the missing configs here and bring them forward. If additional hostnames are listed in those configs that aren't listed above, let me know and we'll decide whether to keep them.

**Comment by floatingatoll** [comment]
I broke down the hostnames I was able to find in _today's_ DNS here in an internal doc:

https://docs.google.com/spreadsheets/d/1tcn78gL-FwcKswiC2Mioul2T39C1HdHXPX8B-ej2I2c/edit#gid=0

Any hostnames I didn't list that are present in the configs may have been removed from DNS over time, in which case we'll document that they're no longer in DNS and remove them.

**Comment by floatingatoll** [comment]
Thanks to @mconnormoz for reporting this issue to IT.

**Comment by floatingatoll** [comment]
Various useful links:

https://github.com/mozilla-it/haul/blob/f28daa3966832139e97312c5033b917eb9f78259/nubis/puppet/sites.pp#L40

https://bugzilla.mozilla.org/show_bug.cgi?id=1491329 — Firefox PM bug

https://bugzilla.mozilla.org/show_bug.cgi?id=1491380 — DNS research bug for *.start.mozilla.org

**Comment by floatingatoll** [comment]
Looks good, r? me on the pull request.

**Comment by floatingatoll** [comment]
We were unable to configure Traefik to handle these domains correctly, so this issue has migrated to:

https://bugzilla.mozilla.org/show_bug.cgi?id=1491411
