### ISSUE TITLE
planet.mozilla.org/projects is not available

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/haul#39]
The Planet build container is failing to generate content for the `projects` planet. This issue was reported here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1421778

I made a minor change to the container (changing relative paths to full paths) which seems to solve this issue. `dhartnell/mozilla-planet-builder:4.5` was pushed to Docker Hub and it should solve the issue. I'll update `planet-mozilla.groovy` to use the newer container and validate that the site still builds successfully for the stage environment. After that, I can update the other Planet Groovy files and plan a production deploy.

**Comment by danielhartnell** [comment]
For a little clarification on what was happening:

The build script in the datacenter had the following:

```
for planet in $PLANETS; do
    cd $planet
    /usr/bin/python2.7 ../../../planet-source/trunk/planet.py config.ini >> $LOGFILE 2>&1
    cd ..
done
```

I mirrored this when I carried that script into the Docker container for building the planet sites. You can probably see the issue. If the $planet directory does not exist, it fails and then bounces back a directory when it executes `cd ..`. Subsequent loops will continue to fail.

I just removed the use of relative paths in the script:

```
#!/bin/bash

PLANET_SOURCE=/data/genericrhel6/build/planet-source
PLANET_CONTENT=/data/genericrhel6/build/planet-content
...
for planet in $PLANETS; do
    cd $PLANET_CONTENT/branches/$planet
    DIR=$(grep ^output_dir config.ini | awk '{print $3}')
    sed -i "s|^cache_directory.*|cache_directory = $DIR\/.cache\/|" $PLANET_CONTENT/branches/$planet/config.ini
    python $PLANET_SOURCE/trunk/planet.py $PLANET_CONTENT/branches/$planet/config.ini
    cd $PLANET_CONTENT/branches
done
```

You can review the `planet-build.sh` script (formerly `planet-prod.sh`) here if you want: 

- https://github.com/danielhartnell/haul/tree/issue-39-planet-build/build-containers/planet
- (Or the corresponding PR) https://github.com/mozilla-it/haul/pull/40

If you want to view the older version used by `dhartnell/mozilla-planet-builder:4.3` you'll have to run that container and look at the script: `/usr/local/bin/planet-prod.sh`.

**Comment by floatingatoll** [comment]
Hi, I’d like to offer two general bash comments for your consideration
(either here or in the future).

This script would likely benefit from “set -e”, so that it halts on any
error (including cd) rather than continuing blindly.

If you’d like a more resilient approach then cd, you could pursue instead:

for; do
  pushd $TARGET && {
    Stuff
    popd
  }
done

Or you could simply remove the trailing cd and use “set -e”, since there’s
no point in calling cd twice in row with two different targets on every
loop.

Food for thought, cheers.
