### ISSUE TITLE
Traefik did not renew site certificates 30 days out

### ISSUE THREAD

**Issue by ziegeer** [mozilla-it/haul#54]
Today we got an alert in [bug 1429069](https://bugzilla.mozilla.org/show_bug.cgi?id=1429069) that the SSL cert for static.mozilla.com which resides on Haul was expiring in 14 days.  It appears that Traefik may  [hard-code](https://github.com/containous/traefik/blob/master/acme/account.go#L239) a 30-day buffer for renewals before certs expire so it appears that Traefik was not properly renewing certs.

**Comment by danielhartnell** [comment]
See #55 as well.
