### ISSUE TITLE
Prefer rsync over cp -r

### ISSUE THREAD

**Issue by gozer** [mozilla-it/haul#7]
For instance: 
https://github.com/mozilla-it/haul/blob/2a5bfe88e872ae3e6e4d39ef46972380ccf417f4/sites/planet-de.groovy#L13

vs:
```
rsync -av /data/genericrhel6/src/planet.mozilla.de/ dst/
```

WIll not only only copy what has changed, but will also only show what has changed.

**Comment by limed** [comment]
Fixed in e878ada1b1e84fcac25d42c9359ae66c7512802f
